version: "3.9"
services:
  db:
    image: mysql:8
    container_name: auth_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass 
      MYSQL_DATABASE: auth_api             
      MYSQL_USER: auth_user                
      MYSQL_PASSWORD: auth_pass            
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
